version: 2.1

jobs:
  debricked-scan:
    docker:
      - image: debricked/cli
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: debricked scan --no-fingerprint=true debricked  -e "'**/src/**'" 
      #(default [**/node_modules/**,**/vendor/**,**/.git/**,**/obj/**,**/bower_components/

workflows:
  debricked:
    jobs:
      - debricked-scan
