steps:
  - label: ":shield: Debricked"
    command:
      - bash /buildkite.sh
    plugins:
      - docker#v3.3.0:
          image: "debricked/debricked-scan"
          mount-buildkite-agent: true
          environment:
              - "DEBRICKED_TOKEN"
              - "BUILDKITE_REPO"
              - "BUILDKITE_COMMIT"
              - "BUILDKITE_BRANCH"
          entrypoint: ""
          shell : ["/bin/sh", "-e", "-c"]
